
strictness: high

max-line-length: 120

member-warnings: true

doc-warnings: false

test-warnings: false

pylint:
  options:
    init-import: true
    dummy-variables-rgx: _$|dummy|___
  disable:
    - invalid-name
    - too-many-locals

